// lib/medical/safetyKeywords.js

export const SAFETY_KEYWORDS = {
  emergency: [
    "chest pain",
    "tight chest",
    "pressure in chest",
    "cant breathe",
    "can’t breathe",
    "difficulty breathing",
    "shortness of breath",
    "breathing stops",
    "wheezing suddenly",
    "slurred speech",
    "face drooping",
    "weakness on one side",
    "sudden numbness",
    "sudden confusion",
    "sudden vision loss",
    "severe headache",
    "bleeding a lot",
    "blood everywhere",
    "deep wound",
    "unconscious",
    "passed out",
    "hit my head hard",
    "major accident",
    "throat closing",
    "severe allergic reaction",
    "anaphylaxis",
    "radiating pain to arm",
    "pain in left arm",
    "cold sweat",
    "collapsed",
  ],

  selfHarm: [
    "kill myself",
    "want to die",
    "end my life",
    "suicidal",
    "hurt myself",
    "cut myself",
    "self harm",
    "i don't want to live",
    "i dont want to live",
    "how to die",
    "easiest way to die",
    "i’m done with life",
    "im done with life",
  ],

  dosing: [
    "how much should i take",
    "how many mg",
    "how many milligrams",
    "mg",
    "milligrams",
    "increase my dose",
    "decrease my dose",
    "adjust my dose",
    "adjust my insulin",
    "change my medication",
    "double dose",
    "overdose",
    "took too many pills",
    "dose",
    "dosage",
    "how often should i take",
    "is this dose safe",
    "is ___ mg enough",
  ],

  unsafeTreatment: [
    "how to inject",
    "how to remove",
    "how to drain",
    "how to fix it myself",
    "home surgery",
    "diy surgery",
    "diy stitches",
    "treat at home without doctor",
    "remove it myself",
    "how to get antibiotics",
    "prescribe me",
    "give me antibiotics",
    "how to get prescription",
  ],

  //safe topics you can allow (useful if you want to classify)
  safeTopics: [
    "fever",
    "sore throat",
    "cough",
    "runny nose",
    "flu symptoms",
    "headache",
    "rash",
    "nausea",
    "diarrhea",
    "stomach pain",
    "what is diabetes",
    "what is high blood pressure",
    "explain asthma",
    "what causes migraine",
    "why do allergies happen",
    "sleep better tips",
    "nutrition",
    "exercise",
    "stress reduction",
    "prevent colds",
  ],
};
